spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/filmreview_dev
    username: devuser
    password: devpassword
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  
  liquibase:
    enabled: true

logging:
  level:
    com.filmreview: DEBUG
    org.hibernate.SQL: DEBUG
